[package]
authors = ["Michael Daffin <michael@daffin.io>"]
name = "adventofcode"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]

